근태관리		Attendance
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)	ATTDATE(PK)	DATE	NOT NULL
출근시간	ATTSTARTTIME	DATE	NULL
퇴근시간	ATTENDTIME	DATE	NULL

insert into Attendance(USERID,ATTDATE,ATTSTARTTIME,ATTENDTIME)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD'),TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'),
        TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'));
--출첵


        
