근태관리		Attendance
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)	ATTDATE(PK)	DATE	NOT NULL
출근시간	ATTSTARTTIME	DATE	NULL
퇴근시간	ATTENDTIME	DATE	NULL

insert into Attendance(USERID,ATTDATE,ATTSTARTTIME,ATTENDTIME)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD'),TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'),
        TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'));
--출첵


Update Attendance SET ATTENDTIME = TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss')
where userid = ? and ATTDATE= TO_CHAR(SYSDATE,'YY-MM-DD');
--퇴첵

휴가
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)(FK)	ATTDATE(PK)(FK)	DATE	NOT NULL
휴가사유	HOLREASON	VARCHAR2(1000)	NOT NULL
휴가시작날짜	HOLSTART	DATE	NOT NULL
휴가종료날짜	HOLEND	DATE	NOT NULL

insert into Holiday(USERID,ATTDATE,HOLREASON,HOLSTART,HOLEND)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD'),?,?,?);

조퇴	Leave
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)(FK)	ATTDATE(PK)(FK)	DATE	NOT NULL
조퇴사유	LVREASON	VARCHAR2(1000)	NOT NULL

insert into Leave(USERID,ATTDATE,LVREASON)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'),?);

지각	Lateness
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)(FK)	ATTDATE(PK)(FK)	DATE	NOT NULL
지각사유	LTREASON	VARCHAR2(1000)	NOT NULL

insert into Lateness(USERID,ATTDATE,LTREASON)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD hh24:mi:ss'),?);

결근	Absence
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)(FK)	ATTDATE(PK)(FK)	DATE	NOT NULL
결근사유	ABREASON	VARCHAR2(1000)	NOT NULL

insert into Absence(USERID,ATTDATE,ABREASON)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD'),?);

출장 	BizTrip
아이디(PK)(FK)	USERID(PK)(FK)	VARCHAR2(50)	NOT NULL
날짜(PK)(FK)	ATTDATE(PK)(FK)	DATE	NOT NULL
출장사유	BTREASON	VARCHAR2(1000)	NOT NULL
출장시작날짜	BIZSTART	DATE	NOT NULL
출장종료날짜	BIZEND	DATE	NOT NULL

insert into BizTrip(USERID,ATTDATE,BTREASON,BIZSTART,BIZEND)
values(?,TO_CHAR(SYSDATE,'YYYY-MM-DD'),?,?,?);
