CREATE TABLE ROLES (
	AUTHORITY VARCHAR(50) NOT NULL,
	ROLE_NAME VARCHAR(50),
	CONSTRAINT PK_ROLES PRIMARY KEY(AUTHORITY)
);

CREATE TABLE AUTHORITIES (
	USERid VARCHAR(50) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	CONSTRAINT PK_AUTHORITIES PRIMARY KEY(USERid,AUTHORITY),
	CONSTRAINT FK_USERS FOREIGN KEY(USErID) REFERENCES emp(userid),
	CONSTRAINT FK_ROLES3 FOREIGN KEY(AUTHORITY) REFERENCES ROLES(AUTHORITY)
);

insert into roles VALUES('ROLE_USER', 'ROLE_USER');
insert into roles VALUES('ROLE_ADMIN', 'ROLE_ADMIN');


insert into AUTHORITIES VALUES('m1', 'ROLE_USER');
insert into AUTHORITIES VALUES('m2', 'ROLE_USER');
insert into AUTHORITIES VALUES('m3', 'ROLE_USER');
insert into AUTHORITIES VALUES('m4', 'ROLE_USER');
insert into AUTHORITIES VALUES('m5', 'ROLE_USER');
insert into AUTHORITIES VALUES('m6', 'ROLE_USER');
insert into AUTHORITIES VALUES('admin', 'ROLE_ADMIN');